---

- name: Deploy containers
  ansible.builtin.include_tasks:
    file: main/container.yml
      # loop: "{{ podman_containers | dict2items(key_name='name', value_name='container') }}"
  loop: "{{ filter_container }}"
  loop_control:
    label: "{{ item.container.name }}"
  vars:
    container: "{{ item.container }}"
    filter_container:
      "{{ podman_containers
          | dict2items(key_name='name', value_name='container')
          | selectattr('name', 'match', container_select | default('.*'))
          | list
      }}"
